### ISSUE TITLE
Hello World Issues

### ISSUE THREAD

**Issue by AlessandroMinali** [owlbear-rodeo/sdk-tutorials#1]
Hello world example is over 30MB!

This bodes poorly if this is the baseline for an extension.

Possible Improvements:
1. Instead of using `Vite` the tutorial should just a plain and boring html/css/javascript static page. This decreases barrier of entry instead of recommending complex tools. Can easily host/serve extensions via github pages.
2. Package the sdk so that it can be served via a CDN without requiring a build step
3. Reduce dependencies in the sdk [1](https://github.com/owlbear-rodeo/sdk/pull/6) [2](https://github.com/owlbear-rodeo/sdk/pull/5)
4. Profit

Here's an example "Hello World" extension that I made that is 20x smaller than what's given in the tutorial which follows the above suggestions
https://github.com/AlessandroMinali/kiss-dice/blob/master/index.html

**Comment by mitchemmc** [comment]
Using web build tools (like Vite) is a beautiful way to onramp someone into modern web development.
Creating a hello world this way means that new developers can easily extend into languages like typescript or frameworks like React or Vue which are great to use with OBR extensions. Especially if you're trying to match the OBR visual style as we use React internally. (You can see an example of this in the initiative tracker here https://github.com/owlbear-rodeo/initiative-tracker).

Also the "30MB" number you are quoting above is the size before building. Once you build the project the size is only 24KB (Gzipped)
Proof:
![Screenshot 2023-11-13 at 8 06 07 am](https://github.com/owlbear-rodeo/sdk-tutorials/assets/7615006/92e82fcc-7d0c-445a-8c06-531134b1c2be)

In fact the the screenshot above of the bundle size is over 7x bigger then the actual hello world example.

I'll comment on the reduced dependencies on the actual issues themselves but I don't consider a 1KB dependency (like UUID) much of an issue.

Edit::
I just did a test because I was curious about real world size.
If you open the dev tools on the hello world example (without the images) then the actual size the end user is downloading  is 14kB.
<img width="193" alt="image" src="https://github.com/owlbear-rodeo/sdk-tutorials/assets/7615006/bdcdd72e-19ca-41e6-9bd9-9d7706a1e131">
Since your example posted is 12kB I think it is safe to say that using modern dev tools is perfectly fine.
Especially since you get a lot of benefits for development (such as typing and autocomplete) not to mention access to the entire NPM repository.
